### ISSUE TITLE
Failing to pull new commits / updating when GIT_TAG changed.

### ISSUE THREAD

**Issue by WashuHakubi** [jpetrie/fetch-dependency#6]
As the version string no longer includes the GIT_TAG, changing this tag does not cause the dependency to get updated. Instead the version match will compare equal and then fail to pull any new commits.

**Comment by jpetrie** [comment]
Hm, yeah, I guess this broke when I added additional data to the version string beyond the git data. I don't really want to include the git data in the version string because I want `ExternalProject_Add` to handle checking it (then I don't need to duplicate the logic to check if the tag is a branch name, et cetera).

I will probably split the versioning into two files, one for the source info (which may not always be git - I'd like to be able to support transparently switching to a locally-hosted dependency in the future) and one for the rest of the dependency configuration.
